### ISSUE TITLE
Is this compatible with the Form element of shadcn?

### ISSUE THREAD

**Issue by Husain010** [uncvrd/shadcn-ui-date-time-picker#5]
I came across this repo in a discussion online and I wanted to know if this component is compatible with the Form element of shadcn? If so, could you show it how it is done?

**Comment by yourcasualdev** [comment]
I somehow managed to work it with Form element.

```Typescript 
               <FormField
                  control={form.control}
                  name="date"
                  render={({ field }) => (
                    <FormItem className="flex flex-col gap-2 space-y-1 w-full">
                      <FormLabel>Open Date</FormLabel>
                      <Popover>
                        <PopoverTrigger
                          asChild
                          className="py-[2rem] h-12"
                          disabled={
                            jobOpeningLoading || jobOpeningError !== undefined
                          }
                        >
                          <FormControl>
                            <Button
                              variant={'outline'}
                              className={cn(
                                'w-full text-left font-normal py-[0.625rem] h-auto',
                                !field.value && 'text-muted-foreground',
                              )}
                            >
                              {field.value ? (
                                format(field.value, 'PPP')
                              ) : (
                                <span>Pick a date</span>
                              )}
                              <CalendarIcon className="ml-auto h-4 w-4 text-text-quarterary" />
                            </Button>
                          </FormControl>
                        </PopoverTrigger>
                        <PopoverContent className="w-full">
                          <div className="space-y-3">
                            <Calendar
                              mode="single"
                              selected={field.value}
                              onSelect={field.onChange}
                              disabled={(date) => date < new Date()}
                              initialFocus
                            />

                            <TimePicker
                              //@ts-ignore
                              value={
                                field.value
                                  ? {
                                      hour: field.value.getHours(),
                                      minute: field.value.getMinutes(),
                                      second: field.value.getSeconds(),
                                      millisecond:
                                        field.value.getMilliseconds(),
                                    }
                                  : undefined
                              }
                              onChange={async (value) => {
                                // hour: 11;
                                // millisecond: 0;
                                // minute: 0;
                                // second: 0;
                                field.onChange(
                                  moment(field.value)
                                    .hour(value.hour)
                                    .minute(value.minute)
                                    .second(value.second)
                                    .millisecond(value.millisecond)
                                    .toDate(),
                                );
                              }}
                            />
                          </div>
                        </PopoverContent>
                      </Popover>
                    </FormItem>
                  )}
                />
                ```

**Comment by Mehedihasan-95** [comment]
> I somehow managed to work it with Form element.
> 
> ```ts
>                <FormField
>                   control={form.control}
>                   name="date"
>                   render={({ field }) => (
>                     <FormItem className="flex flex-col gap-2 space-y-1 w-full">
>                       <FormLabel>Open Date</FormLabel>
>                       <Popover>
>                         <PopoverTrigger
>                           asChild
>                           className="py-[2rem] h-12"
>                           disabled={
>                             jobOpeningLoading || jobOpeningError !== undefined
>                           }
>                         >
>                           <FormControl>
>                             <Button
>                               variant={'outline'}
>                               className={cn(
>                                 'w-full text-left font-normal py-[0.625rem] h-auto',
>                                 !field.value && 'text-muted-foreground',
>                               )}
>                             >
>                               {field.value ? (
>                                 format(field.value, 'PPP')
>                               ) : (
>                                 <span>Pick a date</span>
>                               )}
>                               <CalendarIcon className="ml-auto h-4 w-4 text-text-quarterary" />
>                             </Button>
>                           </FormControl>
>                         </PopoverTrigger>
>                         <PopoverContent className="w-full">
>                           <div className="space-y-3">
>                             <Calendar
>                               mode="single"
>                               selected={field.value}
>                               onSelect={field.onChange}
>                               disabled={(date) => date < new Date()}
>                               initialFocus
>                             />
> 
>                             <TimePicker
>                               //@ts-ignore
>                               value={
>                                 field.value
>                                   ? {
>                                       hour: field.value.getHours(),
>                                       minute: field.value.getMinutes(),
>                                       second: field.value.getSeconds(),
>                                       millisecond:
>                                         field.value.getMilliseconds(),
>                                     }
>                                   : undefined
>                               }
>                               onChange={async (value) => {
>                                 // hour: 11;
>                                 // millisecond: 0;
>                                 // minute: 0;
>                                 // second: 0;
>                                 field.onChange(
>                                   moment(field.value)
>                                     .hour(value.hour)
>                                     .minute(value.minute)
>                                     .second(value.second)
>                                     .millisecond(value.millisecond)
>                                     .toDate(),
>                                 );
>                               }}
>                             />
>                           </div>
>                         </PopoverContent>
>                       </Popover>
>                     </FormItem>
>                   )}
>                 />
>                 ```
> ```

Cannot find name 'moment'. any idea ? @Nightvision53

**Comment by uncvrd** [comment]
Not sure how i missed this but yes, this is how I use the component @Husain010 :

```
import { fromDate, getLocalTimeZone } from "@internationalized/date"

<FormField<ManageCollectionFormData, "collection.date">
    name="collection.date"
    render={({ field }) => (
        <FormItem>
            <FormLabel>Date</FormLabel>
            <FormControl>
                <DateTimePicker
                    value={
                        !!field.value ? fromDate(DateTime.fromISO(field.value).toJSDate(), getLocalTimeZone()) : null
                    }
                    onChange={(date) => {
                        field.onChange(!!date ? DateTime.fromJSDate(date.toDate(getLocalTimeZone())).toISO() : null)
                    }}
                    shouldCloseOnSelect={false}
                    granularity={"day"}
                />
            </FormControl>
            <FormMessage />
        </FormItem>
    )}
/>
```
