### ISSUE TITLE
Support for 24h time

### ISSUE THREAD

**Issue by berkslv** [uncvrd/shadcn-ui-date-time-picker#6]
Thank you for great component. This component can be support 24h timezone like 18:00, 23:30 or this feature already implemented?

**Comment by uncvrd** [comment]
Hey! yep you should be able to use 24hr timezone, it uses React Aria's `useDatePicker` under the hood which you can change: https://react-spectrum.adobe.com/react-aria/useDatePicker.html#hour-cycle
